/*
 * @file   reg_esp32c6_gpio.h
 * @author David Weber david.weber.dfw@gmail.com
 * @date   11/11/2024
 *
 * @brief reg_esp32c6_gpio module implementation
 *
 * Copyright (C) 2024 David Weber
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __REG_ESP32C6_GPIO_H__
#define __REG_ESP32C6_GPIO_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "reg.h"

//-------------------------------------------------------------------------
// This file is generated by mkreg.py v1.0.0 - DO NOT EDIT
//-------------------------------------------------------------------------
//-------------------------------------------------------------------------
// Edit .def file and regenerate
//-------------------------------------------------------------------------
//-------------------------------------------------------------------------
// Register Definition Data - Used to create this file - DO NOT DELETE
//-------------------------------------------------------------------------
/*
#define GPIO_BASE_ADDR          0x60091000
#define GPIO_PIN_REG_ADDR(n)    (GPIO_BASE_ADDR + 0x0084 + ((n) * 4))
GPIO, SELECT,                   (GPIO_BASE_ADDR + 0x0000), 32, BITS:32
GPIO, OUT,                      (GPIO_BASE_ADDR + 0x0004), 32, RSVD31,RSVD30,D29,D28,D27,D26,D25,D24,D23,D22,D21,D20,D19,D18,D17,D16,D15,D14,D13,D12,RSVD11,RSVD10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0
GPIO, OUT_SET,                  (GPIO_BASE_ADDR + 0x0008), 32, RSVD31,RSVD30,D29,D28,D27,D26,D25,D24,D23,D22,D21,D20,D19,D18,D17,D16,D15,D14,D13,D12,RSVD11,RSVD10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0
GPIO, OUT_CLR,                  (GPIO_BASE_ADDR + 0x000C), 32, RSVD31,RSVD30,D29,D28,D27,D26,D25,D24,D23,D22,D21,D20,D19,D18,D17,D16,D15,D14,D13,D12,RSVD11,RSVD10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0
GPIO, ENABLE,                   (GPIO_BASE_ADDR + 0x0020), 32, RSVD31,RSVD30,D29,D28,D27,D26,D25,D24,D23,D22,D21,D20,D19,D18,D17,D16,D15,D14,D13,D12,RSVD11,RSVD10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0
GPIO, OUT_SET_ENABLE,           (GPIO_BASE_ADDR + 0x0024), 32, RSVD31,RSVD30,D29,D28,D27,D26,D25,D24,D23,D22,D21,D20,D19,D18,D17,D16,D15,D14,D13,D12,RSVD11,RSVD10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0
GPIO, OUT_CLR_ENABLE,           (GPIO_BASE_ADDR + 0x0028), 32, RSVD31,RSVD30,D29,D28,D27,D26,D25,D24,D23,D22,D21,D20,D19,D18,D17,D16,D15,D14,D13,D12,RSVD11,RSVD10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0
GPIO, STRAP,                    (GPIO_BASE_ADDR + 0x0038), 32, RSVD31,RSVD30,D29,D28,D27,D26,D25,D24,D23,D22,D21,D20,D19,D18,D17,D16,D15,D14,D13,D12,RSVD11,RSVD10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0
GPIO, IN,                       (GPIO_BASE_ADDR + 0x003C), 32, RSVD31,RSVD30,D29,D28,D27,D26,D25,D24,D23,D22,D21,D20,D19,D18,D17,D16,D15,D14,D13,D12,RSVD11,RSVD10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0
GPIO, PIN:n,                    (GPIO_PIN_REG_ADDR(n)),    32, RSVD31,RSVD30,D29,D28,D27,D26,D25,D24,D23,D22,D21,D20,D19,D18,D17,D16,D15,D14,D13,D12,RSVD11,RSVD10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0

*/

#define GPIO_BASE_ADDR          0x60091000
#define GPIO_PIN_REG_ADDR(n)    (GPIO_BASE_ADDR + 0x0084 + ((n) * 4))

//------------------------------------------------------------------------------

#ifndef __LANGUAGE_ASM__

typedef union reg_gpio_select_u
{
  uint32_t V;
  struct reg_gpio_select_s
  {
    uint32_t BITS                :32;
  }BF;
} reg_gpio_select_t;

#endif  // __LANGUAGE_ASM__

#define REG_GPIO_SELECT           (*(volatile reg_gpio_select_t*)((GPIO_BASE_ADDR + 0x0000)))
#define REG_GPIO_SELECT_ADDR      (GPIO_BASE_ADDR + 0x0000)

#define BP_GPIO_SELECT_BITS                                     0
#define BM_GPIO_SELECT_BITS                            0xFFFFFFFF

//------------------------------------------------------------------------------

#ifndef __LANGUAGE_ASM__

typedef union reg_gpio_out_u
{
  uint32_t V;
  struct reg_gpio_out_s
  {
    uint32_t D0                  :1;
    uint32_t D1                  :1;
    uint32_t D2                  :1;
    uint32_t D3                  :1;
    uint32_t D4                  :1;
    uint32_t D5                  :1;
    uint32_t D6                  :1;
    uint32_t D7                  :1;
    uint32_t D8                  :1;
    uint32_t D9                  :1;
    uint32_t RSVD10              :1;
    uint32_t RSVD11              :1;
    uint32_t D12                 :1;
    uint32_t D13                 :1;
    uint32_t D14                 :1;
    uint32_t D15                 :1;
    uint32_t D16                 :1;
    uint32_t D17                 :1;
    uint32_t D18                 :1;
    uint32_t D19                 :1;
    uint32_t D20                 :1;
    uint32_t D21                 :1;
    uint32_t D22                 :1;
    uint32_t D23                 :1;
    uint32_t D24                 :1;
    uint32_t D25                 :1;
    uint32_t D26                 :1;
    uint32_t D27                 :1;
    uint32_t D28                 :1;
    uint32_t D29                 :1;
    uint32_t RSVD30              :1;
    uint32_t RSVD31              :1;
  }BF;
} reg_gpio_out_t;

#endif  // __LANGUAGE_ASM__

#define REG_GPIO_OUT           (*(volatile reg_gpio_out_t*)((GPIO_BASE_ADDR + 0x0004)))
#define REG_GPIO_OUT_ADDR      (GPIO_BASE_ADDR + 0x0004)

#define BP_GPIO_OUT_RSVD31                                     31
#define BM_GPIO_OUT_RSVD31                             0x80000000
#define BP_GPIO_OUT_RSVD30                                     30
#define BM_GPIO_OUT_RSVD30                             0x40000000
#define BP_GPIO_OUT_D29                                        29
#define BM_GPIO_OUT_D29                                0x20000000
#define BP_GPIO_OUT_D28                                        28
#define BM_GPIO_OUT_D28                                0x10000000
#define BP_GPIO_OUT_D27                                        27
#define BM_GPIO_OUT_D27                                0x08000000
#define BP_GPIO_OUT_D26                                        26
#define BM_GPIO_OUT_D26                                0x04000000
#define BP_GPIO_OUT_D25                                        25
#define BM_GPIO_OUT_D25                                0x02000000
#define BP_GPIO_OUT_D24                                        24
#define BM_GPIO_OUT_D24                                0x01000000
#define BP_GPIO_OUT_D23                                        23
#define BM_GPIO_OUT_D23                                0x00800000
#define BP_GPIO_OUT_D22                                        22
#define BM_GPIO_OUT_D22                                0x00400000
#define BP_GPIO_OUT_D21                                        21
#define BM_GPIO_OUT_D21                                0x00200000
#define BP_GPIO_OUT_D20                                        20
#define BM_GPIO_OUT_D20                                0x00100000
#define BP_GPIO_OUT_D19                                        19
#define BM_GPIO_OUT_D19                                0x00080000
#define BP_GPIO_OUT_D18                                        18
#define BM_GPIO_OUT_D18                                0x00040000
#define BP_GPIO_OUT_D17                                        17
#define BM_GPIO_OUT_D17                                0x00020000
#define BP_GPIO_OUT_D16                                        16
#define BM_GPIO_OUT_D16                                0x00010000
#define BP_GPIO_OUT_D15                                        15
#define BM_GPIO_OUT_D15                                0x00008000
#define BP_GPIO_OUT_D14                                        14
#define BM_GPIO_OUT_D14                                0x00004000
#define BP_GPIO_OUT_D13                                        13
#define BM_GPIO_OUT_D13                                0x00002000
#define BP_GPIO_OUT_D12                                        12
#define BM_GPIO_OUT_D12                                0x00001000
#define BP_GPIO_OUT_RSVD11                                     11
#define BM_GPIO_OUT_RSVD11                             0x00000800
#define BP_GPIO_OUT_RSVD10                                     10
#define BM_GPIO_OUT_RSVD10                             0x00000400
#define BP_GPIO_OUT_D9                                          9
#define BM_GPIO_OUT_D9                                 0x00000200
#define BP_GPIO_OUT_D8                                          8
#define BM_GPIO_OUT_D8                                 0x00000100
#define BP_GPIO_OUT_D7                                          7
#define BM_GPIO_OUT_D7                                 0x00000080
#define BP_GPIO_OUT_D6                                          6
#define BM_GPIO_OUT_D6                                 0x00000040
#define BP_GPIO_OUT_D5                                          5
#define BM_GPIO_OUT_D5                                 0x00000020
#define BP_GPIO_OUT_D4                                          4
#define BM_GPIO_OUT_D4                                 0x00000010
#define BP_GPIO_OUT_D3                                          3
#define BM_GPIO_OUT_D3                                 0x00000008
#define BP_GPIO_OUT_D2                                          2
#define BM_GPIO_OUT_D2                                 0x00000004
#define BP_GPIO_OUT_D1                                          1
#define BM_GPIO_OUT_D1                                 0x00000002
#define BP_GPIO_OUT_D0                                          0
#define BM_GPIO_OUT_D0                                 0x00000001

//------------------------------------------------------------------------------

#ifndef __LANGUAGE_ASM__

typedef union reg_gpio_out_set_u
{
  uint32_t V;
  struct reg_gpio_out_set_s
  {
    uint32_t D0                  :1;
    uint32_t D1                  :1;
    uint32_t D2                  :1;
    uint32_t D3                  :1;
    uint32_t D4                  :1;
    uint32_t D5                  :1;
    uint32_t D6                  :1;
    uint32_t D7                  :1;
    uint32_t D8                  :1;
    uint32_t D9                  :1;
    uint32_t RSVD10              :1;
    uint32_t RSVD11              :1;
    uint32_t D12                 :1;
    uint32_t D13                 :1;
    uint32_t D14                 :1;
    uint32_t D15                 :1;
    uint32_t D16                 :1;
    uint32_t D17                 :1;
    uint32_t D18                 :1;
    uint32_t D19                 :1;
    uint32_t D20                 :1;
    uint32_t D21                 :1;
    uint32_t D22                 :1;
    uint32_t D23                 :1;
    uint32_t D24                 :1;
    uint32_t D25                 :1;
    uint32_t D26                 :1;
    uint32_t D27                 :1;
    uint32_t D28                 :1;
    uint32_t D29                 :1;
    uint32_t RSVD30              :1;
    uint32_t RSVD31              :1;
  }BF;
} reg_gpio_out_set_t;

#endif  // __LANGUAGE_ASM__

#define REG_GPIO_OUT_SET           (*(volatile reg_gpio_out_set_t*)((GPIO_BASE_ADDR + 0x0008)))
#define REG_GPIO_OUT_SET_ADDR      (GPIO_BASE_ADDR + 0x0008)

#define BP_GPIO_OUT_SET_RSVD31                                 31
#define BM_GPIO_OUT_SET_RSVD31                         0x80000000
#define BP_GPIO_OUT_SET_RSVD30                                 30
#define BM_GPIO_OUT_SET_RSVD30                         0x40000000
#define BP_GPIO_OUT_SET_D29                                    29
#define BM_GPIO_OUT_SET_D29                            0x20000000
#define BP_GPIO_OUT_SET_D28                                    28
#define BM_GPIO_OUT_SET_D28                            0x10000000
#define BP_GPIO_OUT_SET_D27                                    27
#define BM_GPIO_OUT_SET_D27                            0x08000000
#define BP_GPIO_OUT_SET_D26                                    26
#define BM_GPIO_OUT_SET_D26                            0x04000000
#define BP_GPIO_OUT_SET_D25                                    25
#define BM_GPIO_OUT_SET_D25                            0x02000000
#define BP_GPIO_OUT_SET_D24                                    24
#define BM_GPIO_OUT_SET_D24                            0x01000000
#define BP_GPIO_OUT_SET_D23                                    23
#define BM_GPIO_OUT_SET_D23                            0x00800000
#define BP_GPIO_OUT_SET_D22                                    22
#define BM_GPIO_OUT_SET_D22                            0x00400000
#define BP_GPIO_OUT_SET_D21                                    21
#define BM_GPIO_OUT_SET_D21                            0x00200000
#define BP_GPIO_OUT_SET_D20                                    20
#define BM_GPIO_OUT_SET_D20                            0x00100000
#define BP_GPIO_OUT_SET_D19                                    19
#define BM_GPIO_OUT_SET_D19                            0x00080000
#define BP_GPIO_OUT_SET_D18                                    18
#define BM_GPIO_OUT_SET_D18                            0x00040000
#define BP_GPIO_OUT_SET_D17                                    17
#define BM_GPIO_OUT_SET_D17                            0x00020000
#define BP_GPIO_OUT_SET_D16                                    16
#define BM_GPIO_OUT_SET_D16                            0x00010000
#define BP_GPIO_OUT_SET_D15                                    15
#define BM_GPIO_OUT_SET_D15                            0x00008000
#define BP_GPIO_OUT_SET_D14                                    14
#define BM_GPIO_OUT_SET_D14                            0x00004000
#define BP_GPIO_OUT_SET_D13                                    13
#define BM_GPIO_OUT_SET_D13                            0x00002000
#define BP_GPIO_OUT_SET_D12                                    12
#define BM_GPIO_OUT_SET_D12                            0x00001000
#define BP_GPIO_OUT_SET_RSVD11                                 11
#define BM_GPIO_OUT_SET_RSVD11                         0x00000800
#define BP_GPIO_OUT_SET_RSVD10                                 10
#define BM_GPIO_OUT_SET_RSVD10                         0x00000400
#define BP_GPIO_OUT_SET_D9                                      9
#define BM_GPIO_OUT_SET_D9                             0x00000200
#define BP_GPIO_OUT_SET_D8                                      8
#define BM_GPIO_OUT_SET_D8                             0x00000100
#define BP_GPIO_OUT_SET_D7                                      7
#define BM_GPIO_OUT_SET_D7                             0x00000080
#define BP_GPIO_OUT_SET_D6                                      6
#define BM_GPIO_OUT_SET_D6                             0x00000040
#define BP_GPIO_OUT_SET_D5                                      5
#define BM_GPIO_OUT_SET_D5                             0x00000020
#define BP_GPIO_OUT_SET_D4                                      4
#define BM_GPIO_OUT_SET_D4                             0x00000010
#define BP_GPIO_OUT_SET_D3                                      3
#define BM_GPIO_OUT_SET_D3                             0x00000008
#define BP_GPIO_OUT_SET_D2                                      2
#define BM_GPIO_OUT_SET_D2                             0x00000004
#define BP_GPIO_OUT_SET_D1                                      1
#define BM_GPIO_OUT_SET_D1                             0x00000002
#define BP_GPIO_OUT_SET_D0                                      0
#define BM_GPIO_OUT_SET_D0                             0x00000001

//------------------------------------------------------------------------------

#ifndef __LANGUAGE_ASM__

typedef union reg_gpio_out_clr_u
{
  uint32_t V;
  struct reg_gpio_out_clr_s
  {
    uint32_t D0                  :1;
    uint32_t D1                  :1;
    uint32_t D2                  :1;
    uint32_t D3                  :1;
    uint32_t D4                  :1;
    uint32_t D5                  :1;
    uint32_t D6                  :1;
    uint32_t D7                  :1;
    uint32_t D8                  :1;
    uint32_t D9                  :1;
    uint32_t RSVD10              :1;
    uint32_t RSVD11              :1;
    uint32_t D12                 :1;
    uint32_t D13                 :1;
    uint32_t D14                 :1;
    uint32_t D15                 :1;
    uint32_t D16                 :1;
    uint32_t D17                 :1;
    uint32_t D18                 :1;
    uint32_t D19                 :1;
    uint32_t D20                 :1;
    uint32_t D21                 :1;
    uint32_t D22                 :1;
    uint32_t D23                 :1;
    uint32_t D24                 :1;
    uint32_t D25                 :1;
    uint32_t D26                 :1;
    uint32_t D27                 :1;
    uint32_t D28                 :1;
    uint32_t D29                 :1;
    uint32_t RSVD30              :1;
    uint32_t RSVD31              :1;
  }BF;
} reg_gpio_out_clr_t;

#endif  // __LANGUAGE_ASM__

#define REG_GPIO_OUT_CLR           (*(volatile reg_gpio_out_clr_t*)((GPIO_BASE_ADDR + 0x000C)))
#define REG_GPIO_OUT_CLR_ADDR      (GPIO_BASE_ADDR + 0x000C)

#define BP_GPIO_OUT_CLR_RSVD31                                 31
#define BM_GPIO_OUT_CLR_RSVD31                         0x80000000
#define BP_GPIO_OUT_CLR_RSVD30                                 30
#define BM_GPIO_OUT_CLR_RSVD30                         0x40000000
#define BP_GPIO_OUT_CLR_D29                                    29
#define BM_GPIO_OUT_CLR_D29                            0x20000000
#define BP_GPIO_OUT_CLR_D28                                    28
#define BM_GPIO_OUT_CLR_D28                            0x10000000
#define BP_GPIO_OUT_CLR_D27                                    27
#define BM_GPIO_OUT_CLR_D27                            0x08000000
#define BP_GPIO_OUT_CLR_D26                                    26
#define BM_GPIO_OUT_CLR_D26                            0x04000000
#define BP_GPIO_OUT_CLR_D25                                    25
#define BM_GPIO_OUT_CLR_D25                            0x02000000
#define BP_GPIO_OUT_CLR_D24                                    24
#define BM_GPIO_OUT_CLR_D24                            0x01000000
#define BP_GPIO_OUT_CLR_D23                                    23
#define BM_GPIO_OUT_CLR_D23                            0x00800000
#define BP_GPIO_OUT_CLR_D22                                    22
#define BM_GPIO_OUT_CLR_D22                            0x00400000
#define BP_GPIO_OUT_CLR_D21                                    21
#define BM_GPIO_OUT_CLR_D21                            0x00200000
#define BP_GPIO_OUT_CLR_D20                                    20
#define BM_GPIO_OUT_CLR_D20                            0x00100000
#define BP_GPIO_OUT_CLR_D19                                    19
#define BM_GPIO_OUT_CLR_D19                            0x00080000
#define BP_GPIO_OUT_CLR_D18                                    18
#define BM_GPIO_OUT_CLR_D18                            0x00040000
#define BP_GPIO_OUT_CLR_D17                                    17
#define BM_GPIO_OUT_CLR_D17                            0x00020000
#define BP_GPIO_OUT_CLR_D16                                    16
#define BM_GPIO_OUT_CLR_D16                            0x00010000
#define BP_GPIO_OUT_CLR_D15                                    15
#define BM_GPIO_OUT_CLR_D15                            0x00008000
#define BP_GPIO_OUT_CLR_D14                                    14
#define BM_GPIO_OUT_CLR_D14                            0x00004000
#define BP_GPIO_OUT_CLR_D13                                    13
#define BM_GPIO_OUT_CLR_D13                            0x00002000
#define BP_GPIO_OUT_CLR_D12                                    12
#define BM_GPIO_OUT_CLR_D12                            0x00001000
#define BP_GPIO_OUT_CLR_RSVD11                                 11
#define BM_GPIO_OUT_CLR_RSVD11                         0x00000800
#define BP_GPIO_OUT_CLR_RSVD10                                 10
#define BM_GPIO_OUT_CLR_RSVD10                         0x00000400
#define BP_GPIO_OUT_CLR_D9                                      9
#define BM_GPIO_OUT_CLR_D9                             0x00000200
#define BP_GPIO_OUT_CLR_D8                                      8
#define BM_GPIO_OUT_CLR_D8                             0x00000100
#define BP_GPIO_OUT_CLR_D7                                      7
#define BM_GPIO_OUT_CLR_D7                             0x00000080
#define BP_GPIO_OUT_CLR_D6                                      6
#define BM_GPIO_OUT_CLR_D6                             0x00000040
#define BP_GPIO_OUT_CLR_D5                                      5
#define BM_GPIO_OUT_CLR_D5                             0x00000020
#define BP_GPIO_OUT_CLR_D4                                      4
#define BM_GPIO_OUT_CLR_D4                             0x00000010
#define BP_GPIO_OUT_CLR_D3                                      3
#define BM_GPIO_OUT_CLR_D3                             0x00000008
#define BP_GPIO_OUT_CLR_D2                                      2
#define BM_GPIO_OUT_CLR_D2                             0x00000004
#define BP_GPIO_OUT_CLR_D1                                      1
#define BM_GPIO_OUT_CLR_D1                             0x00000002
#define BP_GPIO_OUT_CLR_D0                                      0
#define BM_GPIO_OUT_CLR_D0                             0x00000001

//------------------------------------------------------------------------------

#ifndef __LANGUAGE_ASM__

typedef union reg_gpio_enable_u
{
  uint32_t V;
  struct reg_gpio_enable_s
  {
    uint32_t D0                  :1;
    uint32_t D1                  :1;
    uint32_t D2                  :1;
    uint32_t D3                  :1;
    uint32_t D4                  :1;
    uint32_t D5                  :1;
    uint32_t D6                  :1;
    uint32_t D7                  :1;
    uint32_t D8                  :1;
    uint32_t D9                  :1;
    uint32_t RSVD10              :1;
    uint32_t RSVD11              :1;
    uint32_t D12                 :1;
    uint32_t D13                 :1;
    uint32_t D14                 :1;
    uint32_t D15                 :1;
    uint32_t D16                 :1;
    uint32_t D17                 :1;
    uint32_t D18                 :1;
    uint32_t D19                 :1;
    uint32_t D20                 :1;
    uint32_t D21                 :1;
    uint32_t D22                 :1;
    uint32_t D23                 :1;
    uint32_t D24                 :1;
    uint32_t D25                 :1;
    uint32_t D26                 :1;
    uint32_t D27                 :1;
    uint32_t D28                 :1;
    uint32_t D29                 :1;
    uint32_t RSVD30              :1;
    uint32_t RSVD31              :1;
  }BF;
} reg_gpio_enable_t;

#endif  // __LANGUAGE_ASM__

#define REG_GPIO_ENABLE           (*(volatile reg_gpio_enable_t*)((GPIO_BASE_ADDR + 0x0020)))
#define REG_GPIO_ENABLE_ADDR      (GPIO_BASE_ADDR + 0x0020)

#define BP_GPIO_ENABLE_RSVD31                                  31
#define BM_GPIO_ENABLE_RSVD31                          0x80000000
#define BP_GPIO_ENABLE_RSVD30                                  30
#define BM_GPIO_ENABLE_RSVD30                          0x40000000
#define BP_GPIO_ENABLE_D29                                     29
#define BM_GPIO_ENABLE_D29                             0x20000000
#define BP_GPIO_ENABLE_D28                                     28
#define BM_GPIO_ENABLE_D28                             0x10000000
#define BP_GPIO_ENABLE_D27                                     27
#define BM_GPIO_ENABLE_D27                             0x08000000
#define BP_GPIO_ENABLE_D26                                     26
#define BM_GPIO_ENABLE_D26                             0x04000000
#define BP_GPIO_ENABLE_D25                                     25
#define BM_GPIO_ENABLE_D25                             0x02000000
#define BP_GPIO_ENABLE_D24                                     24
#define BM_GPIO_ENABLE_D24                             0x01000000
#define BP_GPIO_ENABLE_D23                                     23
#define BM_GPIO_ENABLE_D23                             0x00800000
#define BP_GPIO_ENABLE_D22                                     22
#define BM_GPIO_ENABLE_D22                             0x00400000
#define BP_GPIO_ENABLE_D21                                     21
#define BM_GPIO_ENABLE_D21                             0x00200000
#define BP_GPIO_ENABLE_D20                                     20
#define BM_GPIO_ENABLE_D20                             0x00100000
#define BP_GPIO_ENABLE_D19                                     19
#define BM_GPIO_ENABLE_D19                             0x00080000
#define BP_GPIO_ENABLE_D18                                     18
#define BM_GPIO_ENABLE_D18                             0x00040000
#define BP_GPIO_ENABLE_D17                                     17
#define BM_GPIO_ENABLE_D17                             0x00020000
#define BP_GPIO_ENABLE_D16                                     16
#define BM_GPIO_ENABLE_D16                             0x00010000
#define BP_GPIO_ENABLE_D15                                     15
#define BM_GPIO_ENABLE_D15                             0x00008000
#define BP_GPIO_ENABLE_D14                                     14
#define BM_GPIO_ENABLE_D14                             0x00004000
#define BP_GPIO_ENABLE_D13                                     13
#define BM_GPIO_ENABLE_D13                             0x00002000
#define BP_GPIO_ENABLE_D12                                     12
#define BM_GPIO_ENABLE_D12                             0x00001000
#define BP_GPIO_ENABLE_RSVD11                                  11
#define BM_GPIO_ENABLE_RSVD11                          0x00000800
#define BP_GPIO_ENABLE_RSVD10                                  10
#define BM_GPIO_ENABLE_RSVD10                          0x00000400
#define BP_GPIO_ENABLE_D9                                       9
#define BM_GPIO_ENABLE_D9                              0x00000200
#define BP_GPIO_ENABLE_D8                                       8
#define BM_GPIO_ENABLE_D8                              0x00000100
#define BP_GPIO_ENABLE_D7                                       7
#define BM_GPIO_ENABLE_D7                              0x00000080
#define BP_GPIO_ENABLE_D6                                       6
#define BM_GPIO_ENABLE_D6                              0x00000040
#define BP_GPIO_ENABLE_D5                                       5
#define BM_GPIO_ENABLE_D5                              0x00000020
#define BP_GPIO_ENABLE_D4                                       4
#define BM_GPIO_ENABLE_D4                              0x00000010
#define BP_GPIO_ENABLE_D3                                       3
#define BM_GPIO_ENABLE_D3                              0x00000008
#define BP_GPIO_ENABLE_D2                                       2
#define BM_GPIO_ENABLE_D2                              0x00000004
#define BP_GPIO_ENABLE_D1                                       1
#define BM_GPIO_ENABLE_D1                              0x00000002
#define BP_GPIO_ENABLE_D0                                       0
#define BM_GPIO_ENABLE_D0                              0x00000001

//------------------------------------------------------------------------------

#ifndef __LANGUAGE_ASM__

typedef union reg_gpio_out_set_enable_u
{
  uint32_t V;
  struct reg_gpio_out_set_enable_s
  {
    uint32_t D0                  :1;
    uint32_t D1                  :1;
    uint32_t D2                  :1;
    uint32_t D3                  :1;
    uint32_t D4                  :1;
    uint32_t D5                  :1;
    uint32_t D6                  :1;
    uint32_t D7                  :1;
    uint32_t D8                  :1;
    uint32_t D9                  :1;
    uint32_t RSVD10              :1;
    uint32_t RSVD11              :1;
    uint32_t D12                 :1;
    uint32_t D13                 :1;
    uint32_t D14                 :1;
    uint32_t D15                 :1;
    uint32_t D16                 :1;
    uint32_t D17                 :1;
    uint32_t D18                 :1;
    uint32_t D19                 :1;
    uint32_t D20                 :1;
    uint32_t D21                 :1;
    uint32_t D22                 :1;
    uint32_t D23                 :1;
    uint32_t D24                 :1;
    uint32_t D25                 :1;
    uint32_t D26                 :1;
    uint32_t D27                 :1;
    uint32_t D28                 :1;
    uint32_t D29                 :1;
    uint32_t RSVD30              :1;
    uint32_t RSVD31              :1;
  }BF;
} reg_gpio_out_set_enable_t;

#endif  // __LANGUAGE_ASM__

#define REG_GPIO_OUT_SET_ENABLE           (*(volatile reg_gpio_out_set_enable_t*)((GPIO_BASE_ADDR + 0x0024)))
#define REG_GPIO_OUT_SET_ENABLE_ADDR      (GPIO_BASE_ADDR + 0x0024)

#define BP_GPIO_OUT_SET_ENABLE_RSVD31                          31
#define BM_GPIO_OUT_SET_ENABLE_RSVD31                  0x80000000
#define BP_GPIO_OUT_SET_ENABLE_RSVD30                          30
#define BM_GPIO_OUT_SET_ENABLE_RSVD30                  0x40000000
#define BP_GPIO_OUT_SET_ENABLE_D29                             29
#define BM_GPIO_OUT_SET_ENABLE_D29                     0x20000000
#define BP_GPIO_OUT_SET_ENABLE_D28                             28
#define BM_GPIO_OUT_SET_ENABLE_D28                     0x10000000
#define BP_GPIO_OUT_SET_ENABLE_D27                             27
#define BM_GPIO_OUT_SET_ENABLE_D27                     0x08000000
#define BP_GPIO_OUT_SET_ENABLE_D26                             26
#define BM_GPIO_OUT_SET_ENABLE_D26                     0x04000000
#define BP_GPIO_OUT_SET_ENABLE_D25                             25
#define BM_GPIO_OUT_SET_ENABLE_D25                     0x02000000
#define BP_GPIO_OUT_SET_ENABLE_D24                             24
#define BM_GPIO_OUT_SET_ENABLE_D24                     0x01000000
#define BP_GPIO_OUT_SET_ENABLE_D23                             23
#define BM_GPIO_OUT_SET_ENABLE_D23                     0x00800000
#define BP_GPIO_OUT_SET_ENABLE_D22                             22
#define BM_GPIO_OUT_SET_ENABLE_D22                     0x00400000
#define BP_GPIO_OUT_SET_ENABLE_D21                             21
#define BM_GPIO_OUT_SET_ENABLE_D21                     0x00200000
#define BP_GPIO_OUT_SET_ENABLE_D20                             20
#define BM_GPIO_OUT_SET_ENABLE_D20                     0x00100000
#define BP_GPIO_OUT_SET_ENABLE_D19                             19
#define BM_GPIO_OUT_SET_ENABLE_D19                     0x00080000
#define BP_GPIO_OUT_SET_ENABLE_D18                             18
#define BM_GPIO_OUT_SET_ENABLE_D18                     0x00040000
#define BP_GPIO_OUT_SET_ENABLE_D17                             17
#define BM_GPIO_OUT_SET_ENABLE_D17                     0x00020000
#define BP_GPIO_OUT_SET_ENABLE_D16                             16
#define BM_GPIO_OUT_SET_ENABLE_D16                     0x00010000
#define BP_GPIO_OUT_SET_ENABLE_D15                             15
#define BM_GPIO_OUT_SET_ENABLE_D15                     0x00008000
#define BP_GPIO_OUT_SET_ENABLE_D14                             14
#define BM_GPIO_OUT_SET_ENABLE_D14                     0x00004000
#define BP_GPIO_OUT_SET_ENABLE_D13                             13
#define BM_GPIO_OUT_SET_ENABLE_D13                     0x00002000
#define BP_GPIO_OUT_SET_ENABLE_D12                             12
#define BM_GPIO_OUT_SET_ENABLE_D12                     0x00001000
#define BP_GPIO_OUT_SET_ENABLE_RSVD11                          11
#define BM_GPIO_OUT_SET_ENABLE_RSVD11                  0x00000800
#define BP_GPIO_OUT_SET_ENABLE_RSVD10                          10
#define BM_GPIO_OUT_SET_ENABLE_RSVD10                  0x00000400
#define BP_GPIO_OUT_SET_ENABLE_D9                               9
#define BM_GPIO_OUT_SET_ENABLE_D9                      0x00000200
#define BP_GPIO_OUT_SET_ENABLE_D8                               8
#define BM_GPIO_OUT_SET_ENABLE_D8                      0x00000100
#define BP_GPIO_OUT_SET_ENABLE_D7                               7
#define BM_GPIO_OUT_SET_ENABLE_D7                      0x00000080
#define BP_GPIO_OUT_SET_ENABLE_D6                               6
#define BM_GPIO_OUT_SET_ENABLE_D6                      0x00000040
#define BP_GPIO_OUT_SET_ENABLE_D5                               5
#define BM_GPIO_OUT_SET_ENABLE_D5                      0x00000020
#define BP_GPIO_OUT_SET_ENABLE_D4                               4
#define BM_GPIO_OUT_SET_ENABLE_D4                      0x00000010
#define BP_GPIO_OUT_SET_ENABLE_D3                               3
#define BM_GPIO_OUT_SET_ENABLE_D3                      0x00000008
#define BP_GPIO_OUT_SET_ENABLE_D2                               2
#define BM_GPIO_OUT_SET_ENABLE_D2                      0x00000004
#define BP_GPIO_OUT_SET_ENABLE_D1                               1
#define BM_GPIO_OUT_SET_ENABLE_D1                      0x00000002
#define BP_GPIO_OUT_SET_ENABLE_D0                               0
#define BM_GPIO_OUT_SET_ENABLE_D0                      0x00000001

//------------------------------------------------------------------------------

#ifndef __LANGUAGE_ASM__

typedef union reg_gpio_out_clr_enable_u
{
  uint32_t V;
  struct reg_gpio_out_clr_enable_s
  {
    uint32_t D0                  :1;
    uint32_t D1                  :1;
    uint32_t D2                  :1;
    uint32_t D3                  :1;
    uint32_t D4                  :1;
    uint32_t D5                  :1;
    uint32_t D6                  :1;
    uint32_t D7                  :1;
    uint32_t D8                  :1;
    uint32_t D9                  :1;
    uint32_t RSVD10              :1;
    uint32_t RSVD11              :1;
    uint32_t D12                 :1;
    uint32_t D13                 :1;
    uint32_t D14                 :1;
    uint32_t D15                 :1;
    uint32_t D16                 :1;
    uint32_t D17                 :1;
    uint32_t D18                 :1;
    uint32_t D19                 :1;
    uint32_t D20                 :1;
    uint32_t D21                 :1;
    uint32_t D22                 :1;
    uint32_t D23                 :1;
    uint32_t D24                 :1;
    uint32_t D25                 :1;
    uint32_t D26                 :1;
    uint32_t D27                 :1;
    uint32_t D28                 :1;
    uint32_t D29                 :1;
    uint32_t RSVD30              :1;
    uint32_t RSVD31              :1;
  }BF;
} reg_gpio_out_clr_enable_t;

#endif  // __LANGUAGE_ASM__

#define REG_GPIO_OUT_CLR_ENABLE           (*(volatile reg_gpio_out_clr_enable_t*)((GPIO_BASE_ADDR + 0x0028)))
#define REG_GPIO_OUT_CLR_ENABLE_ADDR      (GPIO_BASE_ADDR + 0x0028)

#define BP_GPIO_OUT_CLR_ENABLE_RSVD31                          31
#define BM_GPIO_OUT_CLR_ENABLE_RSVD31                  0x80000000
#define BP_GPIO_OUT_CLR_ENABLE_RSVD30                          30
#define BM_GPIO_OUT_CLR_ENABLE_RSVD30                  0x40000000
#define BP_GPIO_OUT_CLR_ENABLE_D29                             29
#define BM_GPIO_OUT_CLR_ENABLE_D29                     0x20000000
#define BP_GPIO_OUT_CLR_ENABLE_D28                             28
#define BM_GPIO_OUT_CLR_ENABLE_D28                     0x10000000
#define BP_GPIO_OUT_CLR_ENABLE_D27                             27
#define BM_GPIO_OUT_CLR_ENABLE_D27                     0x08000000
#define BP_GPIO_OUT_CLR_ENABLE_D26                             26
#define BM_GPIO_OUT_CLR_ENABLE_D26                     0x04000000
#define BP_GPIO_OUT_CLR_ENABLE_D25                             25
#define BM_GPIO_OUT_CLR_ENABLE_D25                     0x02000000
#define BP_GPIO_OUT_CLR_ENABLE_D24                             24
#define BM_GPIO_OUT_CLR_ENABLE_D24                     0x01000000
#define BP_GPIO_OUT_CLR_ENABLE_D23                             23
#define BM_GPIO_OUT_CLR_ENABLE_D23                     0x00800000
#define BP_GPIO_OUT_CLR_ENABLE_D22                             22
#define BM_GPIO_OUT_CLR_ENABLE_D22                     0x00400000
#define BP_GPIO_OUT_CLR_ENABLE_D21                             21
#define BM_GPIO_OUT_CLR_ENABLE_D21                     0x00200000
#define BP_GPIO_OUT_CLR_ENABLE_D20                             20
#define BM_GPIO_OUT_CLR_ENABLE_D20                     0x00100000
#define BP_GPIO_OUT_CLR_ENABLE_D19                             19
#define BM_GPIO_OUT_CLR_ENABLE_D19                     0x00080000
#define BP_GPIO_OUT_CLR_ENABLE_D18                             18
#define BM_GPIO_OUT_CLR_ENABLE_D18                     0x00040000
#define BP_GPIO_OUT_CLR_ENABLE_D17                             17
#define BM_GPIO_OUT_CLR_ENABLE_D17                     0x00020000
#define BP_GPIO_OUT_CLR_ENABLE_D16                             16
#define BM_GPIO_OUT_CLR_ENABLE_D16                     0x00010000
#define BP_GPIO_OUT_CLR_ENABLE_D15                             15
#define BM_GPIO_OUT_CLR_ENABLE_D15                     0x00008000
#define BP_GPIO_OUT_CLR_ENABLE_D14                             14
#define BM_GPIO_OUT_CLR_ENABLE_D14                     0x00004000
#define BP_GPIO_OUT_CLR_ENABLE_D13                             13
#define BM_GPIO_OUT_CLR_ENABLE_D13                     0x00002000
#define BP_GPIO_OUT_CLR_ENABLE_D12                             12
#define BM_GPIO_OUT_CLR_ENABLE_D12                     0x00001000
#define BP_GPIO_OUT_CLR_ENABLE_RSVD11                          11
#define BM_GPIO_OUT_CLR_ENABLE_RSVD11                  0x00000800
#define BP_GPIO_OUT_CLR_ENABLE_RSVD10                          10
#define BM_GPIO_OUT_CLR_ENABLE_RSVD10                  0x00000400
#define BP_GPIO_OUT_CLR_ENABLE_D9                               9
#define BM_GPIO_OUT_CLR_ENABLE_D9                      0x00000200
#define BP_GPIO_OUT_CLR_ENABLE_D8                               8
#define BM_GPIO_OUT_CLR_ENABLE_D8                      0x00000100
#define BP_GPIO_OUT_CLR_ENABLE_D7                               7
#define BM_GPIO_OUT_CLR_ENABLE_D7                      0x00000080
#define BP_GPIO_OUT_CLR_ENABLE_D6                               6
#define BM_GPIO_OUT_CLR_ENABLE_D6                      0x00000040
#define BP_GPIO_OUT_CLR_ENABLE_D5                               5
#define BM_GPIO_OUT_CLR_ENABLE_D5                      0x00000020
#define BP_GPIO_OUT_CLR_ENABLE_D4                               4
#define BM_GPIO_OUT_CLR_ENABLE_D4                      0x00000010
#define BP_GPIO_OUT_CLR_ENABLE_D3                               3
#define BM_GPIO_OUT_CLR_ENABLE_D3                      0x00000008
#define BP_GPIO_OUT_CLR_ENABLE_D2                               2
#define BM_GPIO_OUT_CLR_ENABLE_D2                      0x00000004
#define BP_GPIO_OUT_CLR_ENABLE_D1                               1
#define BM_GPIO_OUT_CLR_ENABLE_D1                      0x00000002
#define BP_GPIO_OUT_CLR_ENABLE_D0                               0
#define BM_GPIO_OUT_CLR_ENABLE_D0                      0x00000001

//------------------------------------------------------------------------------

#ifndef __LANGUAGE_ASM__

typedef union reg_gpio_strap_u
{
  uint32_t V;
  struct reg_gpio_strap_s
  {
    uint32_t D0                  :1;
    uint32_t D1                  :1;
    uint32_t D2                  :1;
    uint32_t D3                  :1;
    uint32_t D4                  :1;
    uint32_t D5                  :1;
    uint32_t D6                  :1;
    uint32_t D7                  :1;
    uint32_t D8                  :1;
    uint32_t D9                  :1;
    uint32_t RSVD10              :1;
    uint32_t RSVD11              :1;
    uint32_t D12                 :1;
    uint32_t D13                 :1;
    uint32_t D14                 :1;
    uint32_t D15                 :1;
    uint32_t D16                 :1;
    uint32_t D17                 :1;
    uint32_t D18                 :1;
    uint32_t D19                 :1;
    uint32_t D20                 :1;
    uint32_t D21                 :1;
    uint32_t D22                 :1;
    uint32_t D23                 :1;
    uint32_t D24                 :1;
    uint32_t D25                 :1;
    uint32_t D26                 :1;
    uint32_t D27                 :1;
    uint32_t D28                 :1;
    uint32_t D29                 :1;
    uint32_t RSVD30              :1;
    uint32_t RSVD31              :1;
  }BF;
} reg_gpio_strap_t;

#endif  // __LANGUAGE_ASM__

#define REG_GPIO_STRAP           (*(volatile reg_gpio_strap_t*)((GPIO_BASE_ADDR + 0x0038)))
#define REG_GPIO_STRAP_ADDR      (GPIO_BASE_ADDR + 0x0038)

#define BP_GPIO_STRAP_RSVD31                                   31
#define BM_GPIO_STRAP_RSVD31                           0x80000000
#define BP_GPIO_STRAP_RSVD30                                   30
#define BM_GPIO_STRAP_RSVD30                           0x40000000
#define BP_GPIO_STRAP_D29                                      29
#define BM_GPIO_STRAP_D29                              0x20000000
#define BP_GPIO_STRAP_D28                                      28
#define BM_GPIO_STRAP_D28                              0x10000000
#define BP_GPIO_STRAP_D27                                      27
#define BM_GPIO_STRAP_D27                              0x08000000
#define BP_GPIO_STRAP_D26                                      26
#define BM_GPIO_STRAP_D26                              0x04000000
#define BP_GPIO_STRAP_D25                                      25
#define BM_GPIO_STRAP_D25                              0x02000000
#define BP_GPIO_STRAP_D24                                      24
#define BM_GPIO_STRAP_D24                              0x01000000
#define BP_GPIO_STRAP_D23                                      23
#define BM_GPIO_STRAP_D23                              0x00800000
#define BP_GPIO_STRAP_D22                                      22
#define BM_GPIO_STRAP_D22                              0x00400000
#define BP_GPIO_STRAP_D21                                      21
#define BM_GPIO_STRAP_D21                              0x00200000
#define BP_GPIO_STRAP_D20                                      20
#define BM_GPIO_STRAP_D20                              0x00100000
#define BP_GPIO_STRAP_D19                                      19
#define BM_GPIO_STRAP_D19                              0x00080000
#define BP_GPIO_STRAP_D18                                      18
#define BM_GPIO_STRAP_D18                              0x00040000
#define BP_GPIO_STRAP_D17                                      17
#define BM_GPIO_STRAP_D17                              0x00020000
#define BP_GPIO_STRAP_D16                                      16
#define BM_GPIO_STRAP_D16                              0x00010000
#define BP_GPIO_STRAP_D15                                      15
#define BM_GPIO_STRAP_D15                              0x00008000
#define BP_GPIO_STRAP_D14                                      14
#define BM_GPIO_STRAP_D14                              0x00004000
#define BP_GPIO_STRAP_D13                                      13
#define BM_GPIO_STRAP_D13                              0x00002000
#define BP_GPIO_STRAP_D12                                      12
#define BM_GPIO_STRAP_D12                              0x00001000
#define BP_GPIO_STRAP_RSVD11                                   11
#define BM_GPIO_STRAP_RSVD11                           0x00000800
#define BP_GPIO_STRAP_RSVD10                                   10
#define BM_GPIO_STRAP_RSVD10                           0x00000400
#define BP_GPIO_STRAP_D9                                        9
#define BM_GPIO_STRAP_D9                               0x00000200
#define BP_GPIO_STRAP_D8                                        8
#define BM_GPIO_STRAP_D8                               0x00000100
#define BP_GPIO_STRAP_D7                                        7
#define BM_GPIO_STRAP_D7                               0x00000080
#define BP_GPIO_STRAP_D6                                        6
#define BM_GPIO_STRAP_D6                               0x00000040
#define BP_GPIO_STRAP_D5                                        5
#define BM_GPIO_STRAP_D5                               0x00000020
#define BP_GPIO_STRAP_D4                                        4
#define BM_GPIO_STRAP_D4                               0x00000010
#define BP_GPIO_STRAP_D3                                        3
#define BM_GPIO_STRAP_D3                               0x00000008
#define BP_GPIO_STRAP_D2                                        2
#define BM_GPIO_STRAP_D2                               0x00000004
#define BP_GPIO_STRAP_D1                                        1
#define BM_GPIO_STRAP_D1                               0x00000002
#define BP_GPIO_STRAP_D0                                        0
#define BM_GPIO_STRAP_D0                               0x00000001

//------------------------------------------------------------------------------

#ifndef __LANGUAGE_ASM__

typedef union reg_gpio_in_u
{
  uint32_t V;
  struct reg_gpio_in_s
  {
    uint32_t D0                  :1;
    uint32_t D1                  :1;
    uint32_t D2                  :1;
    uint32_t D3                  :1;
    uint32_t D4                  :1;
    uint32_t D5                  :1;
    uint32_t D6                  :1;
    uint32_t D7                  :1;
    uint32_t D8                  :1;
    uint32_t D9                  :1;
    uint32_t RSVD10              :1;
    uint32_t RSVD11              :1;
    uint32_t D12                 :1;
    uint32_t D13                 :1;
    uint32_t D14                 :1;
    uint32_t D15                 :1;
    uint32_t D16                 :1;
    uint32_t D17                 :1;
    uint32_t D18                 :1;
    uint32_t D19                 :1;
    uint32_t D20                 :1;
    uint32_t D21                 :1;
    uint32_t D22                 :1;
    uint32_t D23                 :1;
    uint32_t D24                 :1;
    uint32_t D25                 :1;
    uint32_t D26                 :1;
    uint32_t D27                 :1;
    uint32_t D28                 :1;
    uint32_t D29                 :1;
    uint32_t RSVD30              :1;
    uint32_t RSVD31              :1;
  }BF;
} reg_gpio_in_t;

#endif  // __LANGUAGE_ASM__

#define REG_GPIO_IN           (*(volatile reg_gpio_in_t*)((GPIO_BASE_ADDR + 0x003C)))
#define REG_GPIO_IN_ADDR      (GPIO_BASE_ADDR + 0x003C)

#define BP_GPIO_IN_RSVD31                                      31
#define BM_GPIO_IN_RSVD31                              0x80000000
#define BP_GPIO_IN_RSVD30                                      30
#define BM_GPIO_IN_RSVD30                              0x40000000
#define BP_GPIO_IN_D29                                         29
#define BM_GPIO_IN_D29                                 0x20000000
#define BP_GPIO_IN_D28                                         28
#define BM_GPIO_IN_D28                                 0x10000000
#define BP_GPIO_IN_D27                                         27
#define BM_GPIO_IN_D27                                 0x08000000
#define BP_GPIO_IN_D26                                         26
#define BM_GPIO_IN_D26                                 0x04000000
#define BP_GPIO_IN_D25                                         25
#define BM_GPIO_IN_D25                                 0x02000000
#define BP_GPIO_IN_D24                                         24
#define BM_GPIO_IN_D24                                 0x01000000
#define BP_GPIO_IN_D23                                         23
#define BM_GPIO_IN_D23                                 0x00800000
#define BP_GPIO_IN_D22                                         22
#define BM_GPIO_IN_D22                                 0x00400000
#define BP_GPIO_IN_D21                                         21
#define BM_GPIO_IN_D21                                 0x00200000
#define BP_GPIO_IN_D20                                         20
#define BM_GPIO_IN_D20                                 0x00100000
#define BP_GPIO_IN_D19                                         19
#define BM_GPIO_IN_D19                                 0x00080000
#define BP_GPIO_IN_D18                                         18
#define BM_GPIO_IN_D18                                 0x00040000
#define BP_GPIO_IN_D17                                         17
#define BM_GPIO_IN_D17                                 0x00020000
#define BP_GPIO_IN_D16                                         16
#define BM_GPIO_IN_D16                                 0x00010000
#define BP_GPIO_IN_D15                                         15
#define BM_GPIO_IN_D15                                 0x00008000
#define BP_GPIO_IN_D14                                         14
#define BM_GPIO_IN_D14                                 0x00004000
#define BP_GPIO_IN_D13                                         13
#define BM_GPIO_IN_D13                                 0x00002000
#define BP_GPIO_IN_D12                                         12
#define BM_GPIO_IN_D12                                 0x00001000
#define BP_GPIO_IN_RSVD11                                      11
#define BM_GPIO_IN_RSVD11                              0x00000800
#define BP_GPIO_IN_RSVD10                                      10
#define BM_GPIO_IN_RSVD10                              0x00000400
#define BP_GPIO_IN_D9                                           9
#define BM_GPIO_IN_D9                                  0x00000200
#define BP_GPIO_IN_D8                                           8
#define BM_GPIO_IN_D8                                  0x00000100
#define BP_GPIO_IN_D7                                           7
#define BM_GPIO_IN_D7                                  0x00000080
#define BP_GPIO_IN_D6                                           6
#define BM_GPIO_IN_D6                                  0x00000040
#define BP_GPIO_IN_D5                                           5
#define BM_GPIO_IN_D5                                  0x00000020
#define BP_GPIO_IN_D4                                           4
#define BM_GPIO_IN_D4                                  0x00000010
#define BP_GPIO_IN_D3                                           3
#define BM_GPIO_IN_D3                                  0x00000008
#define BP_GPIO_IN_D2                                           2
#define BM_GPIO_IN_D2                                  0x00000004
#define BP_GPIO_IN_D1                                           1
#define BM_GPIO_IN_D1                                  0x00000002
#define BP_GPIO_IN_D0                                           0
#define BM_GPIO_IN_D0                                  0x00000001

//------------------------------------------------------------------------------

#ifndef __LANGUAGE_ASM__

typedef union reg_gpio_pin_u
{
  uint32_t V;
  struct reg_gpio_pin_s
  {
    uint32_t D0                  :1;
    uint32_t D1                  :1;
    uint32_t D2                  :1;
    uint32_t D3                  :1;
    uint32_t D4                  :1;
    uint32_t D5                  :1;
    uint32_t D6                  :1;
    uint32_t D7                  :1;
    uint32_t D8                  :1;
    uint32_t D9                  :1;
    uint32_t RSVD10              :1;
    uint32_t RSVD11              :1;
    uint32_t D12                 :1;
    uint32_t D13                 :1;
    uint32_t D14                 :1;
    uint32_t D15                 :1;
    uint32_t D16                 :1;
    uint32_t D17                 :1;
    uint32_t D18                 :1;
    uint32_t D19                 :1;
    uint32_t D20                 :1;
    uint32_t D21                 :1;
    uint32_t D22                 :1;
    uint32_t D23                 :1;
    uint32_t D24                 :1;
    uint32_t D25                 :1;
    uint32_t D26                 :1;
    uint32_t D27                 :1;
    uint32_t D28                 :1;
    uint32_t D29                 :1;
    uint32_t RSVD30              :1;
    uint32_t RSVD31              :1;
  }BF;
} reg_gpio_pin_t;

#endif  // __LANGUAGE_ASM__

#define REG_GPIO_PIN(N)       (*(volatile reg_gpio_pin_t*)((GPIO_PIN_REG_ADDR(N))))
#define REG_GPIO_PIN_ADDR(N)  (GPIO_PIN_REG_ADDR(N))

#define BP_GPIO_PIN_RSVD31                                     31
#define BM_GPIO_PIN_RSVD31                             0x80000000
#define BP_GPIO_PIN_RSVD30                                     30
#define BM_GPIO_PIN_RSVD30                             0x40000000
#define BP_GPIO_PIN_D29                                        29
#define BM_GPIO_PIN_D29                                0x20000000
#define BP_GPIO_PIN_D28                                        28
#define BM_GPIO_PIN_D28                                0x10000000
#define BP_GPIO_PIN_D27                                        27
#define BM_GPIO_PIN_D27                                0x08000000
#define BP_GPIO_PIN_D26                                        26
#define BM_GPIO_PIN_D26                                0x04000000
#define BP_GPIO_PIN_D25                                        25
#define BM_GPIO_PIN_D25                                0x02000000
#define BP_GPIO_PIN_D24                                        24
#define BM_GPIO_PIN_D24                                0x01000000
#define BP_GPIO_PIN_D23                                        23
#define BM_GPIO_PIN_D23                                0x00800000
#define BP_GPIO_PIN_D22                                        22
#define BM_GPIO_PIN_D22                                0x00400000
#define BP_GPIO_PIN_D21                                        21
#define BM_GPIO_PIN_D21                                0x00200000
#define BP_GPIO_PIN_D20                                        20
#define BM_GPIO_PIN_D20                                0x00100000
#define BP_GPIO_PIN_D19                                        19
#define BM_GPIO_PIN_D19                                0x00080000
#define BP_GPIO_PIN_D18                                        18
#define BM_GPIO_PIN_D18                                0x00040000
#define BP_GPIO_PIN_D17                                        17
#define BM_GPIO_PIN_D17                                0x00020000
#define BP_GPIO_PIN_D16                                        16
#define BM_GPIO_PIN_D16                                0x00010000
#define BP_GPIO_PIN_D15                                        15
#define BM_GPIO_PIN_D15                                0x00008000
#define BP_GPIO_PIN_D14                                        14
#define BM_GPIO_PIN_D14                                0x00004000
#define BP_GPIO_PIN_D13                                        13
#define BM_GPIO_PIN_D13                                0x00002000
#define BP_GPIO_PIN_D12                                        12
#define BM_GPIO_PIN_D12                                0x00001000
#define BP_GPIO_PIN_RSVD11                                     11
#define BM_GPIO_PIN_RSVD11                             0x00000800
#define BP_GPIO_PIN_RSVD10                                     10
#define BM_GPIO_PIN_RSVD10                             0x00000400
#define BP_GPIO_PIN_D9                                          9
#define BM_GPIO_PIN_D9                                 0x00000200
#define BP_GPIO_PIN_D8                                          8
#define BM_GPIO_PIN_D8                                 0x00000100
#define BP_GPIO_PIN_D7                                          7
#define BM_GPIO_PIN_D7                                 0x00000080
#define BP_GPIO_PIN_D6                                          6
#define BM_GPIO_PIN_D6                                 0x00000040
#define BP_GPIO_PIN_D5                                          5
#define BM_GPIO_PIN_D5                                 0x00000020
#define BP_GPIO_PIN_D4                                          4
#define BM_GPIO_PIN_D4                                 0x00000010
#define BP_GPIO_PIN_D3                                          3
#define BM_GPIO_PIN_D3                                 0x00000008
#define BP_GPIO_PIN_D2                                          2
#define BM_GPIO_PIN_D2                                 0x00000004
#define BP_GPIO_PIN_D1                                          1
#define BM_GPIO_PIN_D1                                 0x00000002
#define BP_GPIO_PIN_D0                                          0
#define BM_GPIO_PIN_D0                                 0x00000001


//-----------------------------------------------------------------------------

#ifdef __cplusplus
}
#endif

#endif //__REG_ESP32C6_GPIO_H__

